high_T:
    command_file: !!str "setup_template.inp"
    input_file: !!str "ala_solv.data"
    run_gamma: !!float "0.01"
    eq_steps: !!int "200000"
    nsim: !!int "1"
    thermo_freq: !!int "1"
    run_steps: !!int "2000000"
    nrestart: !!int "2000"
    dt: !!float "1.0"
    run_temp_list: !!seq [!!float "300.0"]

umbrella:
    plumed_template: !!str "umbrella_template.plumed.dat"
    pull_kappa: !!float "100.0"
    kappa: !!float "24.0"
    phi_windows: !!int "20"
    psi_windows: !!int "20"

analysis:
    natoms: !!int "22"
    target_temp: !!float "300.0"
    N_list: !!seq [!!int "1000",!!int "2000",!!int "5000",!!int "10000",!!int "20000",!!int "26000",!!int "27000",!!int "28000",!!int "29000",!!int "30000",!!int "40000",!!int "50000",int "100000",!!int "150000",!!int "200000"]
    kb: !!float "0.001985875" # kcal/mol
    fes_phi_windows: !!int "100"
    fes_psi_windows: !!int "100"
    tolerance: !!float "0.01"

